# Generated by Django 4.2.7 on 2023-11-21 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrationmodel',
            name='me',
        ),
        migrations.AddField(
            model_name='registrationmodel',
            name='customer_type',
            field=models.IntegerField(blank=True, max_length=14, null=True),
        ),
    ]
